### ISSUE TITLE
[1221a] Recieving a Grey Display when opening img file with Qemu

### ISSUE THREAD

**Issue by ghost** [inobulles/aquabsd#1]
When running the command:  "qemu-system-x86_64 -drive file=aquabsd-beta-0621a.img,format=raw" with the image that you released today, I'm getting a completely grey screen with no desktop and none of the functions working.

**Comment by obiwac** [comment]
That's possibly due to a [bug](https://lists.freebsd.org/archives/freebsd-current/2021-November/000932.html) that was present in aquaBSD core `1021a` and that was fixed in `1121a`. I re-implemented the workaround from `1021a` as that's the version of aquaBSD core that's still being used... I'll have to investigate further. Thank you for the heads up, but I'm not entirely sure when I'll have the time to 1. test under which conditions the bug occurs (in my limited testing, things worked fine) 2. actually release a potential `1221b` version with a fix.

**Comment by obiwac** [comment]
Small update on this issue: I think it was simply a matter of me not using the updated packages since 1021a (notably the new AQUA KOS and devices). When testing locally I use my own, up to date packages, but when building on Cirrus CI I use the release from [`aquabsd-pkg-repo`](https://github.com/inobulles/aquabsd-pkg-repo). I'm taking a look at the issue right now...

**Comment by obiwac** [comment]
Fixed as of `0222a`.

**Comment by obiwac** [comment]
Although not the same issue, a similar problem was occurring since `1121a`, where core commit [`b8cf1c5`](https://github.com/inobulles/aquabsd-core/commit/b8cf1c5c30a5e6da4e2c9702ffd607a90453fb33) stopped statically linking the `vesa` kernel module in the default configuration.

This was fixed in [`aquabsd-builder`](https://github.com/inobulles/aquabsd-builder) by appending `kld_list="vesa"` to the default `/etc/rc.conf`, so as to dynamically load the kernel module.
